// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItkj8FgLLznKTaFCKbj4YhF_xfJijzKI',
    appId: '1:902036746185:android:277e8dc676137291f34218',
    messagingSenderId: '902036746185',
    projectId: 'test-9a170',
    databaseURL: 'https://test-9a170-default-rtdb.firebaseio.com',
    storageBucket: 'test-9a170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gfmMPPKNP9fgGW-kE8TYQQ3whczT3Cw',
    appId: '1:902036746185:ios:313c2026bf3bd1f6f34218',
    messagingSenderId: '902036746185',
    projectId: 'test-9a170',
    databaseURL: 'https://test-9a170-default-rtdb.firebaseio.com',
    storageBucket: 'test-9a170.appspot.com',
    androidClientId: '902036746185-u68dueom5gn3jmeh8vb6ldvsrl38li3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTest1',
  );
}
